-- $BEGIN
CREATE TABLE mamba_fact_insurance
(
    patient_service_bill_id          int            not null,
    consommation_id                  int            not null,
    billable_service_id              int            null,
    service_id                       int            null,
    service_date                     date           not null,
    unit_price                       decimal(20, 2) not null,
    quantity                         decimal(20, 2) null,
    paid_quantity                    decimal(20, 2) null,
    service_other                    varchar(100)   null,
    service_other_description        varchar(250)   null,
    is_paid                          smallint       not null,
    drug_frequency                   varchar(150)   null,
    item_type                        tinyint(1)     null,
    voided                           smallint       not null,
    global_bill_id                   int            null,
    department_id                    int            null,
    beneficiary_id                   int            not null,
    patient_bill_id                  int            not null,
    insurance_bill_id                int            null,
    third_party_bill_id              int            null,
    admission_id                     int            not null,
    insurance_id                     int            null,
    bill_identifier                  varchar(250)   not null,
    global_amount                    decimal        not null,
    closing_date                     datetime       null,
    closed                           smallint       not null,
    closed_by                        int            null,
    closed_reason                    varchar(150)   null,
    edited_by                        int            null,
    edit_reason                      varchar(150)   null,
    global_bill_creation_date        datetime       not null,
    department_name                  varchar(50)    null,
    facility_service_price_id        int            not null,
    service_category_id              int            null,
    maxima_to_pay                    decimal(20, 2) null,
    start_date                       date           not null,
    end_date                         date           null,
    beneficary_patient_id            int            not null,
    insurance_policy_id              int            not null,
    policy_id_number                 varchar(250)   null,
    creator                          int            not null,
    owner_name                       varchar(150)   null,
    owner_code                       varchar(150)   null,
    level                            int            null,
    company                          varchar(100)   null,
    patient_bill_amount              decimal(20, 2) not null,
    is_patient_bill_paid             smallint       null,
    status                           varchar(150)   null,
    insurance_bill_amount            decimal        not null,
    third_party_bill_amount          decimal        not null,
    third_party_id                   int            null,
    insurance_card_no                varchar(250)   null,
    insurance_policy_owner           int            not null,
    coverage_start_date              date           not null,
    expiration_date                  date           null,
    insurance_company_concept        int            null,
    insurance_category               varchar(150)   not null,
    insurance_company_name           varchar(50)    not null,
    insurance_company_address        varchar(150)   null,
    insurance_company_phone          varchar(100)   null,
    owner_patient_id                 int            not null,
    third_party_name                 varchar(150)   not null,
    third_party_rate                 float          not null,
    service_category_name            varchar(150)   not null,
    service_category_price           decimal        null,
    facility_location_id             int            not null,
    facility_concept_id              int            null,
    facility_name                    varchar(150)   not null,
    facility_full_price              decimal(20, 2) not null,
    beneficiary_patient_id           int            not null,
    beneficiary_family_name          varchar(50)    null,
    beneficiary_middle_name          varchar(50)    null,
    beneficiary_given_name           varchar(50)    null,
    beneficiary_birth_date           varchar(255)   null,
    beneficiary_birth_date_estimated tinyint        not null,
    beneficiary_gender               varchar(255)   null
);

create index mamba_fact_insurance_closing_date_index
    on mamba_fact_insurance (closing_date);

create index mamba_fact_insurance_creation_date_index
    on mamba_fact_insurance (global_bill_creation_date);

create index mamba_fact_insurance_insurance_id_index
    on mamba_fact_insurance (insurance_id);
-- $END

